trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:

- job:
  pool:
    vmImage: ubuntu-latest
  container: abstudelft/ghdl-gcc-python:latest
  steps:
  - script: |
      python3 setup.py build 
    displayName: Build
  - script: |
      python3 setup.py test
    displayName: Test
  - script: |
      python3 setup.py lint
    displayName: Lint
  - script: |
      python3 setup.py bdist_wheel
    displayName: Wheel
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/nosetests.xml'
  - task: UseDotNet@2
    inputs:
      version: 2.x
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
  - script: |
      bash <(curl https://codecov.io/bash) -f coverage.xml
    env:
      CODECOV_TOKEN: $(codecov)
    displayName: codecov
  - script: |
      pip3 install --user twine
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: Install twine
  - task: TwineAuthenticate@0
    inputs:
      externalFeeds: 'testpypi'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: Authenticate Twine
  - script: |
      'python3 -m twine upload -r https://test.pypi.org/legacy/ --config-file $(PYPIRC_PATH) dist/*'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: Publish to PyPi
