#!/usr/bin/env python3
import sys
with open('vsim.log', 'w') as fildes:
    if '-do' in sys.argv:
        fname = sys.argv[sys.argv.index('-do') + 1]
        print('executing do file: ' + fname)
        with open(fname, 'r') as do_file:
            fildes.write(do_file.read())
    else:
        print('executing from stdin')
        fildes.write(sys.stdin.read())
